version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: fitness-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: Vojislav123!
      MYSQL_DATABASE: app_db
      MYSQL_USER: root
      MYSQL_PASSWORD: Vojislav123!
    command: [
      "--default-authentication-plugin=mysql_native_password",
      "--character-set-server=utf8mb4",
      "--collation-server=utf8mb4_unicode_ci"
    ]
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-uroot", "-pVojislav123!"]
      interval: 10s
      timeout: 5s
      retries: 10

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: fitness-backend
    restart: unless-stopped
    environment:
      DB_USER: root
      DB_PASSWORD: Vojislav123!
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: app_db
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: fitness-frontend
    restart: unless-stopped
    environment:
      VITE_API_URL: http://backend:8080
    depends_on:
      - backend
    ports:
      - "5173:5173"

  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: fitness-swagger
    restart: unless-stopped
    environment:
      SWAGGER_JSON_URL: /openapi.yaml
      BASE_URL: /
    volumes:
      - ./backend/docs/openapi.yaml:/usr/share/nginx/html/openapi.yaml:ro
    ports:
      - "8081:8080"
    depends_on:
      - backend

volumes:
  db_data:



